# Generated by Django 5.1.3 on 2025-02-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsize_name_alter_productunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='quantity_alert',
            field=models.IntegerField(default=100),
        ),
    ]
