# Generated by Django 5.1.3 on 2025-01-20 04:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_company_id_alter_employee_contact'),
        ('products', '0002_alter_productsize_name_alter_productunit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAddHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('adder', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAddDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField(default=0)),
                ('product_variation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_add_product_variation', to='products.productvariation')),
                ('inventory_add_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryaddheader')),
            ],
        ),
    ]
