# Generated by Django 5.1.3 on 2024-12-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_company_id_alter_employee_contact'),
        ('products', '0002_alter_productsize_name_alter_productunit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceiveDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiveHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequeststatus')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_request', models.PositiveIntegerField(default=0)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_product_variation', to='products.productvariation')),
                ('purchase_request_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequestheader')),
            ],
        ),
    ]
