# Generated by Django 5.1.3 on 2025-01-17 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_company_id_alter_employee_contact'),
        ('purchases', '0002_purchaserequestheader_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestheader',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_approver', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='purchaserequestheader',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_requestor', to='employees.employee'),
        ),
    ]
