# Generated by Django 5.1.3 on 2025-01-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchasereceivedetail_product_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereceivedetail',
            old_name='quantity_receive',
            new_name='quantity_received',
        ),
    ]
