# Generated by Django 5.1.3 on 2025-01-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchasereceivestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiveheader',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchasereceivestatus'),
        ),
    ]
