# Generated by Django 5.1.3 on 2024-11-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position_specialties',
        ),
        migrations.AddField(
            model_name='employee',
            name='position_specialties',
            field=models.ManyToManyField(blank=True, to='employees.employeejobspecialty'),
        ),
    ]
