# Generated by Django 5.1.3 on 2024-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_position_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
