# Generated by Django 5.1.3 on 2025-01-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesinvoiceheader_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoicedetail',
            old_name='sales_invoice_header',
            new_name='sale_invoice_header',
        ),
    ]
