# Generated by Django 5.1.3 on 2025-01-20 09:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_company_id_alter_employee_contact'),
        ('products', '0002_alter_productsize_name_alter_productunit_name'),
        ('sales', '0003_rename_sales_invoice_header_saleinvoicedetail_sale_invoice_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialReceiptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialReceiptHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_receipt_creator', to='employees.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.officialreceiptstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_paid', models.PositiveIntegerField(default=0)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_receipt_product_variation', to='products.productvariation')),
                ('official_receipt_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.officialreceiptheader')),
            ],
        ),
    ]
